// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urkdqcjzrkxlbmbcggau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVya2RxY2p6cmt4bGJtYmNnZ2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDQ4NzgsImV4cCI6MjA2MTIyMDg3OH0.gzkgJ6QDsa8ZfMm5Y5tRE7sLqZ8QCCudDje7wRfcP7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);